### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by heyitstay11** [Prathyusha-Guduru/Investor-Calculator#1]
Description

Submitting unfilled form throws a *500* error.

 Cause

**Non validated input** , using input type text.

Solution

- Use input type number for taking inputs from the user instead of text,
- Use min and required attribute of input tag to do some built in validation

[Link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#min)

-----
![ServerErr1](https://user-images.githubusercontent.com/74863317/111317993-a6624900-868a-11eb-8a70-c8afa4a72cb9.PNG)

**Comment by Prathyusha-Guduru** [comment]
Thank you will do it right now

**Comment by Prathyusha-Guduru** [comment]
Updated form validation using wtform validators!
